# full name (with extension) of the image to be drawn
image_file: star_outline.jpg

# desired height, in cm, from the base plane of the arm (the table where the arm is mounted)
pen_elevation: 4.0 # 21

# width of the paper on which the drawing is made
paper_width: 50.0

# height of the paper on which the drawing is made
paper_length: 50.0

# desired coverage of the drawing, in cm, as a percentage. For example, 80 = cover 80% of the paper
coverage: 80

# position of the center of the image, in cm, along x (left / right) with respect to the arm's base
# increasing this values moves the center of the image towards the left
image_center_x: 49

# position of the center of the image, in cm, along y (up / down) with respect to the arm's base
# increasing this values moves the center of the image towards the bottom
image_center_y: 0
