# full name (with extension) of the image to be drawn
image_file: trees.svg

# desired height, in cm, from the base plane of the arm (the table where the arm is mounted)
pen_height: 18.8

# width of the paper on which the drawing is made, in cm
paper_width: 60.0

# height of the paper on which the drawing is made, in cm
paper_length: 90.0

# desired coverage of the drawing, as a percentage. For example, 80 = cover 80% of the paper
coverage: 56

# the rate at which the height of the pen is reduced in cm/hour. For example 0.2 = decrease height by 0.2cm (or 2mm) every hour
height_rate: 0.00 # cm per hour. for example 0.04 means 0.4 mm per hour

# vertical position of the center of the image (up / down), in cm, with respect to the arm's base
# increasing this values moves the center of the image up the paper
image_center_x: 51 # 44.5

# horizontal position of the center of the image (left / right), in cm, with respect to the arm's base
# increasing this values moves the center of the image towards the left of the paper
image_center_y: 10

# Saved values for pen height
# 15.4 PRANG peel off HB
# 19.7 Paris Conte Charcoal 20 July
# 13.2 - creata color monolith HB
# 16 (approx. not working) - carbon sketch
# 19.7 LEAD CREATCOLOR CHARCOAL holder 19.7 height  0.08 pressure
# 18.5 HEEIGHT FOR CALLIGRAPHIC PENCIL cALLI CREATIVE iTALIC
# 17.0 preppy federhalter
# 18.8 Calli Italic 
